"""initial schema

Revision ID: ada766b187c5
Revises: 
Create Date: 2026-08-12 08:07:59.185323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ada766b187c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_nodes',
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'DRAINING', 'OFFLINE', 'DEGRADED', name='browser_node_status'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active_sessions', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('runtime', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('groups',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.Enum('NETWORK', 'DOWNLOADS', 'UPLOADS', 'CLIPBOARD', 'BROWSER', 'SESSION', 'MIME', 'SOURCE', name='policy_type'), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['policy_versions.id'], name='fk_policy_current_version', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('group_policies',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'policy_id', name='uq_group_policy')
    )
    op.create_index(op.f('ix_group_policies_group_id'), 'group_policies', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_policies_policy_id'), 'group_policies', ['policy_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('browser_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'STARTING', 'ACTIVE', 'DISCONNECTED', 'ISOLATING', 'ISOLATED', 'TERMINATING', 'TERMINATED', 'FAILED', name='session_status'), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('sandbox_backend', sa.String(length=64), nullable=False),
    sa.Column('display_backend', sa.String(length=64), nullable=False),
    sa.Column('cpu_limit', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('ram_limit_mb', sa.Integer(), nullable=False),
    sa.Column('pid_limit', sa.Integer(), nullable=False),
    sa.Column('disk_limit_mb', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['browser_nodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_node_id'), 'browser_sessions', ['node_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_user_id'), 'browser_sessions', ['user_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SUPERSEDED', name='policy_version_status'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version_number', name='uq_policy_version_number')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    # use_alter=True on policies.current_version_id (circular FK to
    # policy_versions, which doesn't exist yet when 'policies' is created)
    # is excluded from the inline CREATE TABLE DDL; autogenerate does not
    # emit the follow-up ALTER TABLE for it, so it must be added explicitly.
    op.create_foreign_key(
        'fk_policy_current_version', 'policies', 'policy_versions', ['current_version_id'], ['id']
    )
    op.create_table('recovery_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_table('user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_user_id'), 'user_groups', ['user_id'], unique=False)
    op.create_table('file_policy_rules',
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('MIME', 'SOURCE', name='file_rule_type'), nullable=False),
    sa.Column('match_pattern', sa.String(length=512), nullable=False),
    sa.Column('action', sa.Enum('AUTO_RELEASE', 'QUARANTINE', 'DENY', name='file_action'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_policy_rules_policy_version_id'), 'file_policy_rules', ['policy_version_id'], unique=False)
    op.create_table('quarantine_files',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=1024), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('declared_mime', sa.String(length=255), nullable=True),
    sa.Column('detected_mime', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('initial_url', sa.String(length=2048), nullable=True),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('redirect_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tls_used', sa.Boolean(), nullable=True),
    sa.Column('scanner_status', sa.Enum('PENDING', 'SCANNING', 'CLEAN', 'INFECTED', 'ERROR', name='scanner_status'), nullable=False),
    sa.Column('scanner_result', sa.String(length=1024), nullable=True),
    sa.Column('policy_action', sa.Enum('AUTO_RELEASE', 'QUARANTINE', 'DENY', name='file_action_result'), nullable=True),
    sa.Column('policy_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_SCAN', 'SCANNING', 'QUARANTINED', 'RELEASED', 'REJECTED', 'DELETED', name='quarantine_status'), nullable=False),
    sa.Column('storage_object_id', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_comment', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantine_files_session_id'), 'quarantine_files', ['session_id'], unique=False)
    op.create_index(op.f('ix_quarantine_files_sha256'), 'quarantine_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_quarantine_files_source_host'), 'quarantine_files', ['source_host'], unique=False)
    op.create_index(op.f('ix_quarantine_files_user_id'), 'quarantine_files', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'INVESTIGATING', 'RESOLVED', 'FALSE_POSITIVE', name='incident_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('quarantine_file_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['quarantine_file_id'], ['quarantine_files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_session_id'), 'incidents', ['session_id'], unique=False)
    op.create_index(op.f('ix_incidents_user_id'), 'incidents', ['user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('event_type', sa.Enum('USER_CREATED', 'USER_DISABLED', 'USER_ENABLED', 'USER_LOGIN', 'USER_LOGIN_FAILED', 'MFA_ENROLLED', 'MFA_FAILED', 'MFA_RESET', 'RECOVERY_CODE_USED', 'SESSION_STARTED', 'SESSION_DISCONNECTED', 'SESSION_ISOLATED', 'SESSION_RESTORED', 'SESSION_TERMINATED', 'NETWORK_ACCESS_BLOCKED', 'DOWNLOAD_REQUESTED', 'DOWNLOAD_BLOCKED', 'FILE_QUARANTINED', 'FILE_RELEASED', 'FILE_REJECTED', 'MALWARE_DETECTED', 'POLICY_CHANGED', 'POLICY_PUBLISHED', 'NODE_DRAINED', name='security_event_type'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('quarantine_file_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quarantine_file_id'], ['quarantine_files.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_session_id'), 'security_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_session_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_incidents_user_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_session_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_quarantine_files_user_id'), table_name='quarantine_files')
    op.drop_index(op.f('ix_quarantine_files_source_host'), table_name='quarantine_files')
    op.drop_index(op.f('ix_quarantine_files_sha256'), table_name='quarantine_files')
    op.drop_index(op.f('ix_quarantine_files_session_id'), table_name='quarantine_files')
    op.drop_table('quarantine_files')
    op.drop_index(op.f('ix_file_policy_rules_policy_version_id'), table_name='file_policy_rules')
    op.drop_table('file_policy_rules')
    op.drop_index(op.f('ix_user_groups_user_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    # Must drop the circular FK before dropping the table it references.
    op.drop_constraint('fk_policy_current_version', 'policies', type_='foreignkey')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_browser_sessions_user_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_node_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_group_policies_policy_id'), table_name='group_policies')
    op.drop_index(op.f('ix_group_policies_group_id'), table_name='group_policies')
    op.drop_table('group_policies')
    op.drop_table('roles')
    op.drop_table('policies')
    op.drop_table('groups')
    op.drop_table('browser_nodes')
    # ### end Alembic commands ###

    # Dropping a table does not drop the PostgreSQL ENUM types backing its
    # sa.Enum columns — without this, a downgrade-then-upgrade cycle fails
    # with "type already exists". Must run after all tables using them are
    # dropped.
    bind = op.get_bind()
    for enum_name in (
        'security_event_type',
        'incident_status',
        'incident_severity',
        'quarantine_status',
        'file_action_result',
        'scanner_status',
        'file_action',
        'file_rule_type',
        'policy_version_status',
        'session_status',
        'policy_type',
        'browser_node_status',
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
